name: Build Catalog Website

on:
  push:
    paths:
      - "products.csv"
      - "docs/images/**"
      - ".github/workflows/build-website.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas

    - name: Generate index.html
      run: |
        python << 'EOF'
        import pandas as pd
        from pathlib import Path

        df = pd.read_csv("products.csv")
        output = Path("docs/index.html")
        html = "<html><head><title>Catalog</title></head><body><h1>Product Catalog</h1><ul>"
        for _, row in df.iterrows():
            sku = row["sku"]
            name = row.get("name", "Unnamed")
            price = row.get("price", "N/A")
            imgs = [i.strip() for i in str(row["image_urls"]).split(",") if i.strip()]
            img_tags = "".join([f'<img src="images/{sku}_{i+1}.jpg" width="100"/>' for i in range(len(imgs))])
            html += f"<li><strong>{name}</strong> - {price} JOD<br>{img_tags}</li>"
        html += "</ul></body></html>"
        output.write_text(html)
        EOF

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
