name: Download and Commit Images

on:
  workflow_dispatch:  # manual trigger only (safe)

jobs:
  download_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas requests

    - name: Download images from product list
      run: |
        python << 'EOF'
        import pandas as pd, os, requests
        from urllib.parse import urlparse
        os.makedirs("docs/images", exist_ok=True)
        df = pd.read_csv("products.csv")
        for idx, row in df.iterrows():
            urls = str(row.get("Images", "")).split(",")
            sku = str(row.get("Handle", f"IMG{idx}"))
            for i, url in enumerate(urls):
                url = url.strip()
                if not url: continue
                filename = f"{sku}_{i+1}.jpg"
                path = f"docs/images/{filename}"
                try:
                    r = requests.get(url, timeout=15)
                    r.raise_for_status()
                    with open(path, "wb") as f:
                        f.write(r.content)
                    print(f"✅ {filename}")
                except Exception as e:
                    print(f"❌ {url}: {e}")
        EOF

    - name: Commit images to repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/images
        git commit -m "Download and commit new product images" || echo "No changes to commit"
        git push
